version: "3.8"

services:
  api:
    image: busybox
    command: tail -f /dev/null
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: ticket_system
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  db-data:
